[features]
seeds = false
[programs.localnet]
lwt_token = "HMzj7gAjsmr12sRiwjKWkkpX6Ace2Fgu1hrH5xJ6hTSs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rahul/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
